# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "982e8c47f8d30ccc83dd519903384fb3"
application_url = "https://easy-stayed-typing-profit.trycloudflare.com"
embedded = true
name = "qr-code-app"
handle = "qr-code-app-320"

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "products/update" ]
  uri = "/webhooks/products_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://easy-stayed-typing-profit.trycloudflare.com/auth/callback",
  "https://easy-stayed-typing-profit.trycloudflare.com/auth/shopify/callback",
  "https://easy-stayed-typing-profit.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
